### PR TITLE
compile error fix

### PR DESCRIPTION
**Pull request by kiroj305**

### CODE REVIEW

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by kjawadDeveloper2** [comment]
Instead of this . If you can do this   
```flutter_screenutil: 5.3.1```

**Comment by kjawadDeveloper2** [comment]
This will enable you not to do any upgrade and nothing will work.

**Comment by kiroj305** [comment]
@kjawadDeveloper2 , it's been fixed again.

**Review by kjawadDeveloper2 — APPROVED** [review]

**Pull request merged**
