### PR TITLE
Added the ios audio configurations.

### PR DESCRIPTION
**Pull request by kjawadDeveloper2**
1) Added the permission in the info file. 
2) Added ios specific audio formats.
3) Home Screen UI fix to not allow the screen to overflow.

### CODE REVIEW

**Review by kiroj305 — APPROVED** [review]
Thank you for adding these fixes

**Comment by kiroj305** [comment]
@kjawadDeveloper2 , does this PR contain all the changes from 2 previous PRs too?

**Comment by kjawadDeveloper2** [comment]
@Tiny-Angel305  It contains only the latest code of the main.

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Pull request merged**
