### PR TITLE
Revise upload and edit

### PR DESCRIPTION
**Pull request by kiroj305**
This pr covers PS-249 completion and partially PS-200 too.
- Refined cosmetics of both `Upload (Choose Format)` & `Edit` screens.
- Added Hashtags param for recipe creation
- Code refactoring

### CODE REVIEW

**Review by mustafapylons — APPROVED** [review]
Looks good to me.

**Comment by kjawadDeveloper2** [comment]
Screenshot_20220511-094530

There should be no header on this screen.

**Comment by kjawadDeveloper2** [comment]
Screenshot_20220511-094524
Different fields are overflowing on the tablet.

**Comment by kjawadDeveloper2** [comment]
Screenshot_20220511-094253
We have this screen in the app but not in design. Kindly confirm with Stefan.

**Comment by kjawadDeveloper2** [comment]
Screenshot_20220511-094248
The design of this screen is also changed.

**Comment by kjawadDeveloper2** [comment]
@Tiny-Angel305 apologies for late review.

**Review by kjawadDeveloper2 — CHANGES_REQUESTED** [review]
Design issues.

**Comment by kiroj305** [comment]
Closing the PR as it's been outdated.

**Pull request closed without merging**
